Controllers/ImagesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using MVCAuth1.Data;
using MVCAuth1.Models;

namespace MVCAuth1.Controllers;

public class ImagesController : Controller
{
    private readonly ApplicationDbContext _dbContext;
    public ImagesController(ApplicationDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public IActionResult List()
    {
        IEnumerable<ImageStore> data = _dbContext.ImageStores;
        foreach(var obj in data)
        {
            obj.ImageDataAsBase64 = Convert.ToBase64String(obj.ImageData);
        }
        return View(data);
    }
    public async Task<IActionResult> ViewDetail(int? id)
    {
        if(id == null)
        {
            return NotFound("Do not specify image id");
        }
        var result = await _dbContext.ImageStores.FindAsync(id);
        if(result == null)
        {
            return NotFound($"Can not find image with id {id}");
        }
        result.ImageDataAsBase64 = Convert.ToBase64String(result.ImageData);
        return View(result);
    }
    public IActionResult Post()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Post(ImageStore data)
    {
        if(data.ImageFile != null)
        {
            byte[] imageBinaryData;
            using(var fs = data.ImageFile.OpenReadStream())
            {
                using var reader = new BinaryReader(fs);
                imageBinaryData = reader.ReadBytes((int)fs.Length);
            }
            data.ImageData = imageBinaryData;
            await _dbContext.ImageStores.AddAsync(data);
            await _dbContext.SaveChangesAsync();
            return Redirect("/Images/List");
        }
        ModelState.AddModelError(string.Empty, "Something went wrong");
        return View();
    }

    public async Task<IActionResult> Delete(int? id)
    {
        var item = await _dbContext.ImageStores.FindAsync(id);
        if(item != null)
        {
            _dbContext.ImageStores.Remove(item);
            await _dbContext.SaveChangesAsync();
        }
        return Redirect("/Images/List");
    }
}

Controllers/ImagesServeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCAuth1.Data;
using MVCAuth1.Models;
using MVCAuth1.Services;

namespace MVCAuth1.Controllers;

//Serve Image As Static File
public class ImagesServeController : Controller
{
    private readonly ApplicationDbContext _dbContext;
    private readonly IImagesServeControllerConfiguration _config;
    private readonly IWebHostEnvironment _env;
    public ImagesServeController(
        ApplicationDbContext dbContext,
        IImagesServeControllerConfiguration imagesServeControllerConfiguration,
        IWebHostEnvironment env
        )
    {
        _dbContext = dbContext;
        _config = imagesServeControllerConfiguration;
        _env = env;
    }

    [HttpGet]
    public PhysicalFileResult Images()
    {
        string storedPath = _config.GetImageStoredPath() ?? "";
        string physicalPath = _env.ContentRootPath +  storedPath + "/20231114140102.png";
        return PhysicalFile(physicalPath, "image/jpeg");
    }
}

Controllers/MessageController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVCAuth1.Data;
using MVCAuth1.Models;

namespace MVCAuth1.Controllers;

[Authorize]
public class MessageController : Controller
{
    private readonly ILogger<MessageController> logger;
    private readonly ApplicationDbContext dbContext;
    public MessageController(ILogger<MessageController> _logger, ApplicationDbContext _dbContext)
    {
        logger = _logger;
        dbContext = _dbContext;
    }
    [HttpGet]
    public IActionResult GetID()
    {
        return View();
    }
    [HttpPost]
    public IActionResult GetID(UIDInputModel uIDInputModel)
    {
        string friendUID = uIDInputModel.FriendUID ?? "fuck";
        
        return Redirect($"/Message/Chat?friendUID={friendUID}");
    }
    public async Task<IActionResult> Chat(string friendUID)
    {
        string? uid = HttpContext.User?.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if(uid == null || friendUID == null)
        {
            return NotFound();
        }
        List<Message> messages = (from message in dbContext.Messages where (message.UserSend.Id == uid && message.UserReceive.Id  == friendUID) || (message.UserReceive.Id == uid && message.UserSend.Id  == friendUID) select message).ToList();
        foreach(var message in messages)
        {   
            var entry = dbContext.Entry(message);
            await entry.Reference((message) => message.UserSend).LoadAsync();
        }
        
        Console.WriteLine("Call Here is Post");
        return View(messages);
    }
}

Views/Shared/_Layout.cshtml
@using System.Security.Claims;
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager;
@inject UserManager<IdentityUser> UserManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCAuth1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCAuth1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCAuth1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Images" asp-action="Post">Upload Image</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Images" asp-action="List">View Images</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ImagesServe" asp-action="Images">Images</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Message" asp-action="GetId">Chat</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
    
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="display: flex;">
        <div class="container">
            &copy; 2024 - MVCAuth1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        @{
            //Get User Id to display
            var uId = ViewContext.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        }
        @if(uId != null){
            <div class="container" style="display: flex; justify-content: end;">
                UID: @uId 
            </div>
        }
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["title"]</title>
</head>
<body>
    <div class="container">
        <main role="main" class="pt-3">
            @RenderBody()
        </main>
    </div>
</body>
</html>